FROM node:16-alpine

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
ENV NODE_ENV production

COPY ./ecosystem.config.js /app/ecosystem.config.js
COPY ./package.json /app/package.json
COPY ./dist/ /app

RUN npm install --production --no-audit
RUN npm install pm2 -g

EXPOSE 8080

CMD [ "pm2-runtime", "ecosystem.config.js" ]